name: Node.js Practice CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20.16
        uses: actions/setup-node@v4
        with:
          node-version: "20.16"
      - run: npm install
      - run: npm run build --prefix client
